# Generated by Django 5.1.1 on 2024-09-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='account_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('follower_count', models.IntegerField(choices=[(1000, '1,000 followers'), (5000, '5,000 followers'), (10000, '10,000 followers')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
