# Generated by Django 5.1.1 on 2024-09-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='follower_count',
            field=models.PositiveIntegerField(),
        ),
    ]
