# Generated by Django 5.1.1 on 2024-09-17 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_account', '0002_account_is_new_alter_account_follower_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyAccountRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('package', models.CharField(max_length=255)),
                ('mpesa_code', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy_account.account')),
            ],
        ),
    ]
