# Generated by Django 5.1.1 on 2024-09-17 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokBoostRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiktok_username', models.CharField(max_length=100)),
                ('follower_package', models.IntegerField(choices=[(1000, '1,000 followers - 2,599 KSH'), (5000, '5,000 followers - 7,500 KSH'), (10000, '10,000 followers - 10,000 KSH'), (50000, '50,000 followers - 25,000 KSH')])),
                ('payment_screenshot', models.ImageField(upload_to='tiktok_payments/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TikTokBoost',
        ),
    ]
