# Generated by Django 5.1.1 on 2024-09-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramBoost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('follower_package', models.IntegerField(choices=[(1000, '1,000 followers - 2,599 KSH'), (5000, '5,000 followers - 7,500 KSH'), (10000, '10,000 followers - 10,000 KSH'), (50000, '50,000 followers - 25,000 KSH')])),
                ('payment_screenshot', models.ImageField(upload_to='instagram_screenshots/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeBoost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_url', models.URLField()),
                ('subscriber_package', models.IntegerField(choices=[(1000, '1,000 subscribers - 2,599 KSH'), (5000, '5,000 subscribers - 7,500 KSH'), (10000, '10,000 subscribers - 10,000 KSH'), (50000, '50,000 subscribers - 25,000 KSH')])),
                ('payment_screenshot', models.ImageField(upload_to='youtube_screenshots/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='tiktokboost',
            old_name='tiktok_username',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='tiktokboost',
            name='payment_screenshot',
            field=models.ImageField(upload_to='tiktok_screenshots/'),
        ),
    ]
