# Generated by Django 5.1.1 on 2024-09-17 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_instagramboostrequest_delete_instagramboost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeBoostRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_channel', models.URLField()),
                ('boost_package', models.CharField(choices=[('1000_subs', '1,000 Subscribers - 5,000 KSH'), ('5000_subs', '5,000 Subscribers - 20,000 KSH'), ('10000_subs', '10,000 Subscribers - 35,000 KSH'), ('50000_subs', '50,000 Subscribers - 75,000 KSH')], max_length=20)),
                ('watch_hours', models.CharField(choices=[('1000_hours', '1,000 Watch Hours - 3,000 KSH'), ('5000_hours', '5,000 Watch Hours - 10,000 KSH'), ('10000_hours', '10,000 Watch Hours - 20,000 KSH'), ('50000_hours', '50,000 Watch Hours - 50,000 KSH')], max_length=20)),
                ('comment_boost', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_screenshot', models.ImageField(upload_to='youtube_payments/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='YouTubeBoost',
        ),
    ]
