# Generated by Django 5.1.1 on 2024-09-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='complaint_screenshots/'),
        ),
        migrations.DeleteModel(
            name='AdminComment',
        ),
    ]
